OT104-39
alkemyTech/OT104-Client pull request #12
Opened 2021-11-25 17:57 UTC by JuanStromanIlz

Added a new component to display the basic info of the organization as well as a button to access to the edit form. Basic styles were used, as the time of this commit we're not set a framework to use, neither the global style of the entire website.
![OT104-39](https://user-images.githubusercontent.com/54681514/143484644-1cfd610e-2ec1-4fac-8aa2-755cf25bb631.png)

2021-12-08 20:14 UTC, esteban-dosztal requested changes

2021-12-08 20:14 UTC, esteban-dosztal commented on src/Components/Organization/OrganizationInfo.module.css
> +}
Falta línea al final del archivo.

2021-12-09 16:28 UTC, JuanStromanIlz commented on src/Components/Organization/OrganizationInfo.module.css
> +}
Listo.

2021-12-09 22:28 UTC, esteban-dosztal approved these changes

2021-12-09 22:28 UTC, merged