Ot104 32
alkemyTech/OT104-Client pull request #17
Opened 2021-11-26 20:12 UTC by CJ-arg

Created an Admin form to post a welcome text and 3 slides with a text each.  
The ticket doesen `t  specify  the endpoint. 
I try to find them in the API, it must be checked.

2021-12-02 11:40 UTC, esteban-dosztal commented on STYLE.txt
> +https://www.care-international.org/
¿Para qué es este archivo? ¿Se puede borrar?

2021-12-02 11:40 UTC, esteban-dosztal commented on src/Components/About/TextoAbout.jsx
> +      const response = await axios.get(`https://jsonplaceholder.typicode.com/posts`)
¿No habría que cambiar la URL acá? ¿Tenemos la URL real para este dato?

2021-12-02 11:40 UTC, esteban-dosztal commented on src/Components/About/TituloAbout.jsx
> +
Borrar espacios en blanco de más.

2021-12-02 13:47 UTC, CJ-arg commented on STYLE.txt
> +https://www.care-international.org/
borrado

2021-12-02 13:48 UTC, CJ-arg commented on src/Components/About/TextoAbout.jsx
> +      const response = await axios.get(`https://jsonplaceholder.typicode.com/posts`)
cambiado

2021-12-02 13:48 UTC, CJ-arg commented on src/Components/About/TituloAbout.jsx
> +
arreglado

2021-12-02 13:48 UTC, CJ-arg commented
hice los tres cambios y le sume en boostrap

2021-12-08 20:56 UTC, esteban-dosztal requested changes

2021-12-08 20:56 UTC, esteban-dosztal commented on src/Components/Admin/homeForm.css
> +}
Agregar línea en blanco al final del archivo, para evitar problemas con Git.

2021-12-08 21:41 UTC, esteban-dosztal approved these changes

2021-12-08 22:44 UTC, merged