Ot104 31
alkemyTech/OT104-Client pull request #20
Opened 2021-11-26 23:38 UTC by amadeodlp

primer commit en la que se añade validación con formik y YUP, descripción con CK editor y request a la API correspondiente. No se agregaron estilos. Se corrigió anterior commit erróneo.

2021-12-02 11:24 UTC, esteban-dosztal requested changes
Borrar los console.log.

2021-12-02 11:29 UTC, esteban-dosztal requested changes
Borrar los console.log.

2021-12-03 17:12 UTC, amadeodlp commented
se borraron los console log y se añadieron cambios de estilo.

2021-12-08 21:05 UTC, esteban-dosztal requested changes

2021-12-08 21:05 UTC, esteban-dosztal commented on src/Components/Members/MembersForm.js
>      console.log(initialValues);
Borrar console.logs.

2021-12-09 00:52 UTC, amadeodlp commented on src/Components/Members/MembersForm.js
>      console.log(initialValues);
corregido y pusheado.

2021-12-09 22:33 UTC, esteban-dosztal approved these changes

2021-12-09 23:18 UTC, merged