Ot104 35
alkemyTech/OT104-Client pull request #21
Opened 2021-11-26 23:39 UTC by amadeodlp

Primer commit en la que se agregan validaciones con formik y YUP, descripción con CK editor y request a la API correspondiente. Se corrigió anterior commit erróneo.

2021-11-28 13:19 UTC, esteban-dosztal commented on src/Components/Members/MembersForm.js
> +    const [message, setMessage] = useState("");
Cuidado con la identación.

2021-11-28 13:19 UTC, esteban-dosztal commented on src/Components/Members/MembersForm.js
> +            console.log(values);
Los console.log no deberían filtrarse a producción (o sea, en un PR).

2021-11-28 17:14 UTC, amadeodlp commented on src/Components/Members/MembersForm.js
> +            console.log(values);
corregido!

2021-12-02 11:22 UTC, esteban-dosztal requested changes
Borrar todos los console.log, no es buena práctica dejarlos en producción.

2021-12-02 11:29 UTC, esteban-dosztal requested changes
Borrar los console.log que quedan en el PR.

2021-12-03 17:12 UTC, amadeodlp commented
se borraron los console log y se añadieron cambios de estilo.

2021-12-08 21:06 UTC, esteban-dosztal requested changes

2021-12-08 21:06 UTC, esteban-dosztal commented on src/Components/Testimonials/TestimonialsForm.js
> +                console.log(error.response.data);
Borrar console.logs.

2021-12-09 00:51 UTC, amadeodlp commented on src/Components/Testimonials/TestimonialsForm.js
> +                console.log(error.response.data);
corregido y pusheado.

2021-12-09 22:35 UTC, esteban-dosztal approved these changes

2021-12-09 23:01 UTC, merged