added react boostrap
alkemyTech/OT104-Client pull request #28
Opened 2021-12-01 23:40 UTC by CJ-arg

sprint 1 only react boostrap added

2021-12-05 20:51 UTC, esteban-dosztal requested changes

2021-12-05 20:51 UTC, esteban-dosztal commented on src/Components/About/About.jsx
> +export default About
Siempre agregar una línea en blanco al final de todos los archivos. Es una buena práctica para que Git funcione correctamente.

2021-12-05 21:26 UTC, CJ-arg commented on src/Components/About/About.jsx
> +export default About
hecho gracias

2021-12-10 21:19 UTC, esteban-dosztal approved these changes

2021-12-11 14:39 UTC, esteban-dosztal approved these changes

2021-12-11 14:51 UTC, merged