services to check
alkemyTech/OT104-Client pull request #29
Opened 2021-12-02 20:26 UTC by CJ-arg

crud novedades

2021-12-05 20:50 UTC, esteban-dosztal requested changes
Poner el tiket Jira como nombre del MR.

2021-12-10 21:19 UTC, esteban-dosztal approved these changes

2021-12-11 14:53 UTC, esteban-dosztal requested changes
Usar el servicio HTTP base.

2021-12-12 15:05 UTC, CJ-arg commented
modifique el servicio de novedades con el servicio de api privada

2021-12-14 00:16 UTC, esteban-dosztal approved these changes

2021-12-14 00:16 UTC, merged