OT104-62
alkemyTech/OT104-Client pull request #32
Opened 2021-12-02 22:02 UTC by JuanStromanIlz

A new table was created to display the different activities, see the details, edit and delete.

2021-12-05 20:48 UTC, esteban-dosztal requested changes

2021-12-05 20:48 UTC, esteban-dosztal commented on src/App.js
> +      <div className='App'>
Borrar código no usado.

2021-12-05 20:48 UTC, esteban-dosztal commented on src/Components/Activities/ActivitiesList.jsx
> +    console.log(res.data.message);
Borrar los console.log; éstos no deberían filtrarse a prod.

2021-12-05 20:48 UTC, esteban-dosztal commented on src/Components/Activities/ActivitiesList.jsx
> +                    <tr key={activity.id}>
Guarda que activity.id creo que es un number, llamar a toString() para convertirlo en string.

2021-12-06 12:13 UTC, JuanStromanIlz commented on src/App.js
> +      <div className='App'>
Done

2021-12-06 12:13 UTC, JuanStromanIlz commented on src/Components/Activities/ActivitiesList.jsx
> +    console.log(res.data.message);
Done

2021-12-06 12:14 UTC, JuanStromanIlz commented on src/Components/Activities/ActivitiesList.jsx
> +                    <tr key={activity.id}>
Done

2021-12-09 23:21 UTC, esteban-dosztal approved these changes

2021-12-09 23:21 UTC, merged