OT104-69
alkemyTech/OT104-Client pull request #34
Opened 2021-12-02 22:31 UTC by FlorAbril

2021-12-05 20:44 UTC, esteban-dosztal requested changes

2021-12-05 20:44 UTC, esteban-dosztal commented on src/Services/privateApiService.js
> +export {Verify}
Guarda, deberia ser VerifyToken en lugar de Verify.

2021-12-05 23:59 UTC, FlorAbril commented on src/Services/privateApiService.js
> +export {Verify}
Ah no me había dado cuenta, ahí lo cambié.

2021-12-09 23:23 UTC, esteban-dosztal approved these changes

2021-12-09 23:23 UTC, merged