OT104-65
alkemyTech/OT104-Client pull request #35
Opened 2021-12-02 22:35 UTC by AlejoAseijas

The BackofficeList component was created, it brings the users of the ONG and shows it through a table. Also added a link to go to backoffice/users /create

2021-12-05 20:43 UTC, esteban-dosztal requested changes

2021-12-05 20:43 UTC, esteban-dosztal commented on src/Components/Backoffice/BackofficeList.jsx
> +import React, { useState, useEffect } from "react";
Quizás un mejor nombre para este archivo sería BackofficeUserList; refleja más qué hace el componente.

2021-12-05 20:43 UTC, esteban-dosztal commented on src/Components/Backoffice/BackofficeList.jsx
> +        "http://ongapi.alkemy.org/api/users?limit=10"
¿Por qué el parámetro limit? El ticket Jira no dice nada acerca de la cantidad de usuarios a mostrar.
Borrar el parámetro limit.

2021-12-05 20:43 UTC, esteban-dosztal commented on src/Components/Backoffice/BackofficeList.jsx
> +                  <tr key={index}>
No usar index como valor del atributo key.

2021-12-05 20:43 UTC, esteban-dosztal commented on src/Components/Backoffice/BackofficeList.jsx
> +              {users.map((data, index) => {
users.map((data quedaría más significativo como users.map((user...

2021-12-05 21:09 UTC, AlejoAseijas commented on src/Components/Backoffice/BackofficeList.jsx
> +import React, { useState, useEffect } from "react";
Si es mucho mas claro ese nombre, gracias.

2021-12-05 21:10 UTC, AlejoAseijas commented on src/Components/Backoffice/BackofficeList.jsx
> +        "http://ongapi.alkemy.org/api/users?limit=10"
Me olvide de sacarlo, lo use para poder trabajar mas comodo.

2021-12-11 14:31 UTC, esteban-dosztal approved these changes

2021-12-11 14:31 UTC, merged