Ot104 60
alkemyTech/OT104-Client pull request #36
Opened 2021-12-02 23:40 UTC by FlorAbril

2021-12-05 20:28 UTC, esteban-dosztal requested changes

2021-12-05 20:28 UTC, esteban-dosztal commented on src/Components/Card/Card.jsx
> +              aria-expanded={showDescription}
Cuando hacemos setShowDescription(!showDescription), recordar pasarle a setShowDescription una función que recibe el valor actual, y que devuelve el nuevo valor.

2021-12-06 00:03 UTC, FlorAbril commented on src/Components/Card/Card.jsx
> +              aria-expanded={showDescription}
Perfecto, ya lo cambio.

2021-12-10 21:37 UTC, esteban-dosztal approved these changes

2021-12-10 21:38 UTC, merged