Ot104 67
alkemyTech/OT104-Client pull request #40
Opened 2021-12-03 21:08 UTC by CJ-arg

terminado

2021-12-05 20:13 UTC, esteban-dosztal requested changes

2021-12-05 20:13 UTC, esteban-dosztal commented on src/App.js
> +      <div className='App'>
Borrar código no usado.

2021-12-05 20:13 UTC, esteban-dosztal commented on src/Components/About/MiembrosAbout.jsx
> +              <Card className="gap-2" bg="light" key={activity.id} style={{ width: '18rem', height: '25rem' }} >
activity.id es un number o un string? Si es un number, llamar a toString() para convertirlo.

2021-12-05 20:13 UTC, esteban-dosztal commented on src/Components/About/MiembrosAbout.jsx
> +  const [aboutText, setAboutText] = useState([]);
aboutText es confuso si va a guardar la lista de miembros, suena como que va a guardar el texto de la página "acerca de". Sería mejor usar memberList o algo parecido.

2021-12-05 21:18 UTC, CJ-arg commented on src/App.js
> +      <div className='App'>
borrado

2021-12-05 21:19 UTC, CJ-arg commented on src/Components/About/MiembrosAbout.jsx
> +              <Card className="gap-2" bg="light" key={activity.id} style={{ width: '18rem', height: '25rem' }} >
fixed

2021-12-05 21:19 UTC, CJ-arg commented on src/Components/About/MiembrosAbout.jsx
> +  const [aboutText, setAboutText] = useState([]);
cambiado

2021-12-11 14:54 UTC, esteban-dosztal approved these changes

2021-12-11 15:21 UTC, merged