OT104-79
alkemyTech/OT104-Client pull request #42
Opened 2021-12-03 21:32 UTC by hartoy

Methods HTTP base for Categories.

2021-12-05 19:57 UTC, esteban-dosztal reviewed
Buen trabajo. Falta usar los servicios HTTP base una vez que éstos estén mergeados en main. También, conectar los componentes de Categories con estos métodos. Pero vas bien.

2021-12-09 11:35 UTC, esteban-dosztal requested changes

2021-12-09 11:35 UTC, esteban-dosztal commented on src/Services/CategoriesService.js
> +const creatCategories = async (categorie) => {
Poner "category" en lugar de "categorie".

2021-12-09 11:35 UTC, esteban-dosztal commented on src/Services/CategoriesService.js
> +const updateCategories = async (id, categorie) => {
Miso acá, va "category".

2021-12-09 13:33 UTC, hartoy commented on src/Services/CategoriesService.js
> +const creatCategories = async (categorie) => {
HECHO

2021-12-09 13:33 UTC, hartoy commented on src/Services/CategoriesService.js
> +const updateCategories = async (id, categorie) => {
HECHO

2021-12-09 23:20 UTC, esteban-dosztal approved these changes

2021-12-09 23:20 UTC, merged