created a activities service
alkemyTech/OT104-Client pull request #47
Opened 2021-12-04 09:38 UTC by edgarfb

I created HTTP methos to the activities.

2021-12-09 11:38 UTC, esteban-dosztal requested changes

2021-12-09 11:38 UTC, esteban-dosztal commented on src/App.js
> +    <>
Al tener <BrowserRouter> como componente root que contiene todo el resto de los componentes, no necesitamos el Fragment.  (<> y </>).

2021-12-09 11:38 UTC, esteban-dosztal commented on src/Services/activitiesService.js
> +const baseUrl = "http://ongapi.alkemy.org/api/";
Dado que en todos los métodos usamos baseUrl + "activities", ¿por qué no setear directamente const baseUrl = "http://ongapi.alkemy.org/api/activities"; ?

2021-12-11 10:38 UTC, edgarfb commented on src/Services/activitiesService.js
> +const baseUrl = "http://ongapi.alkemy.org/api/";
Perfecto, Esteban. Hecho!

2021-12-11 10:38 UTC, edgarfb commented on src/App.js
> +    <>
Perfecto, Esteban. Hecho!

2021-12-11 19:45 UTC, esteban-dosztal approved these changes

2021-12-11 19:52 UTC, merged