Ot104 56
alkemyTech/OT104-Client pull request #54
Opened 2021-12-07 01:04 UTC by amadeodlp

Creado componente para renderizar sección novedades

2021-12-09 11:50 UTC, esteban-dosztal requested changes
Revisar las identaciones.

2021-12-09 11:50 UTC, esteban-dosztal commented on src/Components/Members/MembersForm.js
>  export default MembersForm;
Agregar línea en blanco al final del archivo.

2021-12-09 11:50 UTC, esteban-dosztal commented on src/Components/News/NewsList.js
>                              <li className="card-info" key={element.id}>
Si element.id es un string, dejarlo como está. Si es un number, haver element.id.toString() para convertirlo en un string. El valor del atributo key debe ser siempre un string.

2021-12-14 21:54 UTC, esteban-dosztal requested changes

2021-12-14 21:54 UTC, esteban-dosztal commented on src/Components/News/NewsList.js
> +        .then((response)=>{
Corregir, el await no necesita un .then. Devuelve el resultado de la llamada como si fuese un método síncrono.

2021-12-14 21:54 UTC, esteban-dosztal commented on src/Components/News/NewsList.js
> +            <Spinner animation="grow" />
Corregir la identación de los elementos, si un elemento está dentro de otro, tiene que estar 4 espacios a la derecha de su elemento padre.

2021-12-14 22:01 UTC, amadeodlp commented
Cambios realizados.

2021-12-14 22:02 UTC, merged