Ot104 96
alkemyTech/OT104-Client pull request #77
Opened 2021-12-13 22:51 UTC by edgarfb

I added Loader and Alerts to / and /Nosotros

2021-12-15 22:04 UTC, esteban-dosztal requested changes

2021-12-15 22:04 UTC, esteban-dosztal commented on src/Components/Home/Home.jsx
> +  // uncomment the lines below to get slides from server
¿Qué hay que hacer con este código comentado?

2021-12-16 01:15 UTC, edgarfb commented on src/Components/Home/Home.jsx
> +  // uncomment the lines below to get slides from server
Resuelto

2021-12-17 22:37 UTC, esteban-dosztal approved these changes

2021-12-21 21:07 UTC, esteban-dosztal requested changes

2021-12-21 21:07 UTC, esteban-dosztal commented on src/Components/About/About.jsx
> +  console.log("membersData", membersData);
Borrar console.log, éste y cualquier otro que haya en el PR.

2021-12-21 21:15 UTC, esteban-dosztal approved these changes

2021-12-21 21:15 UTC, merged